[package]
name = "cryxtal-shapeops"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
cryxtal-base = { path = "../cryxtal-base" }
cryxtal-topology = { path = "../cryxtal-topology" }
truck-shapeops.workspace = true
